services:
  ssv-performance-collector:
    image: ssv-performance-collector:${SSV_PERFORMANCE_COLLECTOR_VERSION:-latest}
    build:
      context: ../..
      dockerfile: scripts/ssv-performance-collector/Dockerfile
    environment:
      NETWORK: ${NETWORK:-mainnet}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      CLICKHOUSE_PASSWORD_FILE: /clickhouse-password.txt
    volumes:
      - ../../credentials/clickhouse-password.txt:/clickhouse-password.txt
    networks:
      - ssv-performance-network

#command: |
#  sh -c '
#    echo "0 12 * * * root python /app/ssv-performance-collector.py >> /var/log/cron.log 2>&1" > /etc/cron.d/ssv-collector &&
#    chmod 0644 /etc/cron.d/ssv-collector &&
#    touch /var/log/cron.log &&
#    cron -f
#  '

networks:
  ssv-performance-network:
    driver: bridge