services:
  ssv-performance-collector:
    image: ssv-performance-collector:${SSV_PERFORMANCE_BOT_VERSION:-latest}
    entrypoint: ["/app/entrypoint.sh"]
    hostname: ssv-performance-collector
    environment:
      NETWORK: ${NETWORK:-mainnet}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      CLICKHOUSE_PASSWORD_FILE: /etc/ssv-performance-collector/clickhouse-password.txt
    volumes:
      - ./credentials/clickhouse-password.txt:/etc/ssv-performance-collector/clickhouse-password.txt:ro
    networks:
      - ssv-performance-network

networks:
  ssv-performance-network:
    driver: bridge