version: '3.9'

services:
  ssv-performance-bot:
    image: ssv-performance-bot:latest
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    hostname: ssv-performance-bot
    environment:
      NETWORK: ${NETWORK:-mainnet}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      BOT_DISCORD_CHANNEL_ID: ${BOT_DISCORD_CHANNEL_ID}
      BOT_DM_RECIPIENTS: ${BOT_DM_RECIPIENTS}
      BOT_DAILY_MESSAGE_TIME: ${BOT_DAILY_MESSAGE_TIME:-08:00}
    volumes:
      - ./certs:/certs
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./credentials/discord-token.txt:/etc/vo-performance-bot/credentials/discord-token.txt:ro
      - ./credentials/clickhouse-password.txt:/etc/ssv-performance-bot/clickhouse-password.txt:ro
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - ssv-performance-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      CLICKHOUSE_PASSWORD_FILE: /etc/ssv-performance-bot/clickhouse-password.txt
    entrypoint: ["/usr/local/bin/clickhouse-entrypoint.sh"]
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-init/clickhouse-entrypoint.sh:/usr/local/bin/clickhouse-entrypoint.sh:ro
      - ./clickhouse-init:/docker-entrypoint-initdb.d
      - ./credentials/clickhouse-password.txt:/etc/ssv-performance-bot/clickhouse-password.txt:ro
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host=localhost", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - ssv-performance-network


volumes:
  clickhouse-data:

networks:
  ssv-performance-network:
    driver: bridge