services:
  ssv-performance-bot:
    image: ssv-performance-bot:${SSV_PERFORMANCE_BOT_VERSION:-latest}
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    hostname: ssv-performance-bot
    environment:
      NETWORK: ${NETWORK:-mainnet}
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      BOT_DISCORD_CHANNEL_ID: ${BOT_DISCORD_CHANNEL_ID}
      BOT_DM_RECIPIENTS: ${BOT_DM_RECIPIENTS:-}
      BOT_DAILY_MESSAGE_TIME: ${BOT_DAILY_MESSAGE_TIME:-08:00}
      CLICKHOUSE_PASSWORD_FILE: /etc/ssv-performance-bot/clickhouse-password.txt
    volumes:
      - ./certs:/certs
      - ./ssv-performance-bot/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./credentials/discord-token.txt:/etc/ssv-performance-bot/discord-token.txt:ro
      - ./credentials/clickhouse-password.txt:/etc/ssv-performance-bot/clickhouse-password.txt:ro
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - ssv-performance-network

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION:-latest}
    hostname: clickhouse
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      CLICKHOUSE_PASSWORD_FILE: /etc/ssv-performance-bot/clickhouse-password.txt
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./clickhouse-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./credentials/clickhouse-password.txt:/etc/ssv-performance-bot/clickhouse-password.txt:ro
      - ./clickhouse-init/healthcheck.sh:/usr/local/bin/healthcheck.sh:ro
      - ./sql-import:/sql-import:ro
      - ./scripts/clickhouse-import/clickhouse-import.sh:/usr/local/bin/clickhouse-import.sh:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 10s
    networks:
      - ssv-performance-network


volumes:
  clickhouse-data:

networks:
  ssv-performance-network:
    driver: bridge
