version: '3.9'

services:
  ssv-performance-bot:
    image: ssv-performance-bot:latest
    hostname: ssv-performance-bot
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      BOT_DISCORD_TOKEN_FILE: /etc/vo-performance-bot/credentials/discord-token.txt
      BOT_DISCORD_CHANNEL_ID: ${BOT_DISCORD_CHANNEL_ID}
      BOT_DM_RECIPIENTS: ${BOT_DM_RECIPIENTS}
      BOT_DAILY_MESSAGE_TIME: ${BOT_DAILY_MESSAGE_TIME:-07:00}
    volumes:
      - ../certs:/certs
      - ../credentials/discord-token.txt:/etc/vo-performance-bot/credentials/discord-token.txt
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - ssv-performance-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    ports:
      - "8124:8123"  # ClickHouse HTTP interface
      - "9001:9000"  # ClickHouse native interface
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST:-clickhouse}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-ssv_performance}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ../clickhouse-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host=localhost", "--query", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - ssv-performance-network


volumes:
  clickhouse-data:

networks:
  ssv-performance-network:
    driver: bridge