MAX_DISCORD_MESSAGE_LENGTH = 2000

OPERATOR_24H_HISTORY_COUNT = 7

FIELD_OPERATOR_ID = 'OperatorID'
FIELD_OPERATOR_NAME = 'Name'
FIELD_IS_VO = 'isVO'
FIELD_IS_PRIVATE = 'isPrivate'
FIELD_VALIDATOR_COUNT = 'ValidatorCount'
FIELD_ADDRESS = 'Address'
FIELD_OPERATOR_UPDATED_AT = 'OperatorUpdatedAt'
FIELD_OPERATOR_REMOVED = 'OperatorRemoved'
FIELD_PERF_DATA_1H = 'Performance1h'
FIELD_PERF_DATA_24H = 'Performance24h'
FIELD_PERF_DATA_30D = 'Performance30d'
FIELD_PERF_DATA_90D = 'Performance90d'
FIELD_PERFORMANCE = 'Performance'
FIELD_PERFORMANCE_DATE = 'PerformanceDate'
FIELD_OPERATOR_FEE = 'OperatorFee'
FIELD_OPERATOR_FEE_DATE = 'OperatorFeeDate'
FIELD_NETWORK = 'Network'

ALERTS_THRESHOLDS_24H = {0.95, 0.75}
ALERTS_THRESHOLDS_30D = {0.98}

DEFAULT_NUMBER_OF_SEGMENTS = 20